### ISSUE TITLE
doesn't work in firefox

### ISSUE THREAD

**Issue by farvardin** [2dengine/love.js#1]
hello,

it doesn't seem to work in Firefox...

I've tried it both on local, and on https://2dengine.com/play/skullbasher

I got a 

```
Uncaught TypeError: indexedDB.databases is not a function
    consentDialog http://localhost/lovejs2/love.js/player.js:105
    onclick http://localhost/lovejs2/love.js/player.js:83
```

**Comment by 2dengine** [comment]
I have pushed a fix that allows the games to run in FireFox but there is a caveat:
the fonts are not rendered correctly on Ubuntu. The fonts seem to work fine in FireFox on Windows.

**Comment by farvardin** [comment]
thank you!
